# Generated by Django 3.2.7 on 2021-09-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpages',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staticpages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_menu', to='menu.staticpages'),
        ),
    ]
